mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://116.62.148.208:3306/e3mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
# redis-single
    host: 116.62.148.208
    port: 6379

dubbo:
  application:
    name: e3-order
  registry:
    address: zookeeper://116.62.148.208:2181
  scan:
    basePackages: guo.ping.e3mall.order.service
  protocol:
    port: 20885