mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: run2sunny
    url: jdbc:mysql://172.16.125.40:3306/e3mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
      timeout: 5000
      host: 172.16.125.40
      port: 6379

  activemq:
        user: admin
        password: admin
        broker-url: tcp://172.16.125.40:61616
        pool:
          enabled: true
          max-connections: 50
        packages:
          trust-all: false

dubbo:
  application:
    name: e3-manager
  registry:
    address: zookeeper://172.16.125.40:2181
  scan:
    basePackages: guo.ping.e3mall.manager.service
  protocol:
    port: 20880